import {
  AlignCenter,
  AlignCenterVertical,
  AlignEndVertical,
  AlignHorizontalSpaceAround,
  AlignLeft,
  AlignRight,
  AlignStartVertical,
  AlignVerticalSpaceAround,
  ArrowDown,
  ArrowUp,
  ArrowUpRight,
  Bold,
  BringToFront,
  Circle,
  Copy,
  Crosshair,
  CornerDownRight,
  Download,
  Eraser,
  GripHorizontal,
  GripVertical,
  Group,
  Hand,
  Highlighter,
  Image,
  Grid3x3,
  Lock,
  Magnet,
  MessageSquare,
  LockOpen,
  Minus,
  Moon,
  MousePointer2,
  Pen,
  Presentation,
  Redo2,
  Scan,
  SendToBack,
  Slash,
  Spline,
  Square,
  StickyNote,
  Sun,
  Trash2,
  Triangle,
  Type,
  Undo2,
  Ungroup,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  select: MousePointer2,
  laser: Crosshair,
  pen: Pen,
  highlighter: Highlighter,
  eraser: Eraser,
  pan: Hand,
  rect: Square,
  ellipse: Circle,
  triangle: Triangle,
  line: Slash,
  arrow: ArrowUpRight,
  text: Type,
  sticky: StickyNote,
  comment: MessageSquare,
  connector: Spline,
  image: Image,
  undo: Undo2,
  redo: Redo2,
  sun: Sun,
  moon: Moon,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  trash: Trash2,
  'grip-vertical': GripVertical,
  'grip-horizontal': GripHorizontal,
  copy: Copy,
  lock: Lock,
  unlock: LockOpen,
  front: BringToFront,
  back: SendToBack,
  forward: ArrowUp,
  backward: ArrowDown,
  group: Group,
  ungroup: Ungroup,
  'align-left': AlignLeft,
  'align-center': AlignCenter,
  'align-right': AlignRight,
  'align-top': AlignStartVertical,
  'align-middle': AlignCenterVertical,
  'align-bottom': AlignEndVertical,
  'distribute-h': AlignHorizontalSpaceAround,
  'distribute-v': AlignVerticalSpaceAround,
  bold: Bold,
  fit: Scan,
  export: Download,
  grid: Grid3x3,
  present: Presentation,
  snap: Magnet,
  straight: Minus,
  elbow: CornerDownRight,
  curve: Spline,
};

export function Icon({ name }: { name: string }) {
  const Glyph = ICONS[name];
  if (!Glyph) return null;
  return <Glyph size={18} strokeWidth={1.8} aria-hidden />;
}
